-- PR-RESET-DATA-02: Reset 탭 스트레칭 전용 템플릿 R01–R10 (M01–M48 풀과 분리된 scoring_version=reset_v1).
-- 동영상 에셋: ops/reset-media manifest + mux-reset-upload → 후속 apply-reset-media-refresh 로 media_ref JSONB 채움.

INSERT INTO public.exercise_templates (
  id,
  name,
  level,
  focus_tags,
  contraindications,
  equipment,
  duration_sec,
  media_ref,
  template_version,
  scoring_version,
  is_fallback,
  is_active
) VALUES
  (
    'R01_STERNOCLEIDOMASTOID_STRETCH',
    '흉쇄유돌근 스트레칭',
    1,
    ARRAY['neck_mobility', 'upper_trap_release']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R02_QUADRICEPS_STRETCH',
    '대퇴 사두근 스트레칭',
    1,
    ARRAY['hip_flexor_stretch']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R03_HAMSTRING_STRETCH',
    '햄스트링 스트레칭',
    1,
    ARRAY['hip_mobility', 'lower_chain_stability']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R04_SEATED_PIRIFORMIS_STRETCH',
    '이상근 스트레칭(앉아서)',
    1,
    ARRAY['hip_mobility']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R05_GLUTEUS_MAXIMUS_STRETCH',
    '대둔근 스트레칭',
    1,
    ARRAY['glute_activation', 'hip_mobility']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R06_SUPINE_PIRIFORMIS_STRETCH',
    '이상근 스트레칭(누워서)',
    1,
    ARRAY['hip_mobility']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R07_CAT_COW_SPINE_STRETCH',
    '캣카우(허리) 스트레칭',
    1,
    ARRAY['thoracic_mobility', 'core_control']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R08_FOAM_ROLLER_LAT_STRETCH',
    '폼롤러 광배근 스트레칭',
    1,
    ARRAY['shoulder_mobility', 'thoracic_mobility']::text[],
    '{}',
    ARRAY['foam_roller']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R09_LONGITUDINAL_FOAM_ROLLER_CHEST_OPENER',
    '폼롤러 세로로 두고 위에 눕기',
    1,
    ARRAY['thoracic_mobility', 'shoulder_mobility']::text[],
    '{}',
    ARRAY['foam_roller']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  ),
  (
    'R10_LEVATOR_SCAPULAE_UPPER_TRAP_STRETCH',
    '견갑거근&상부 승모근 스트레칭',
    1,
    ARRAY['neck_mobility', 'upper_trap_release']::text[],
    '{}',
    ARRAY['bodyweight']::text[],
    180,
    NULL,
    1,
    'reset_v1',
    FALSE,
    TRUE
  )
ON CONFLICT (id) DO NOTHING;
